version: "2"
services:
  postgres:
    container_name: "wallet_invest_postgres_development"
    image: "postgres:9.6.11"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: wallet_invest
      POSTGRES_PASSWORD: wallet_invest@password
      POSTGRES_DB: root
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
